server:
  port: 8080

spring:
  application:
    name: almara-backend

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
      timeout: 2000ms

almara:
  emocion:
    # Lapso de bloqueo para la misma sesión/dispositivo (Criterio 1: 15 minutos = 900 segundos)
    segundos-bloqueo: 900
